node.default['bind9']['base_dir'] = "/etc/bind"
node.default['bind9']['search'] = "role:bind9_server"
node.default['bind9']['options'] = {}
node.default['bind9']['options']['forwarders'] = ["8.8.8.8", "8.8.4.4"]
node.default['bind9']['options']['allow_recursion'] = "10.0.0.0/8"
node.default['bind9']['options']['allow_query'] = "10.0.0.0/8"
node.default['bind9']['options']['allow_query_cache'] = "10.0.0.0/8"
node.default['bind9']['options']['auth_nxdomain'] = "no"
node.default['bind9']['options']['listen_on_v6'] = "none"
